global:
  scrape_interval: 15s

rule_files:
  - "/etc/prometheus/rules/*.yaml"
  - "/etc/prometheus/recording-rules.yaml"

scrape_configs:
  - job_name: 'payment-processing-system'
    static_configs:
      - targets: ['payment-processing-system:8080'] # Prometheus обращается к сервису по его имени в Docker-сети

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']