groups:
  - name: service_alerts
    rules:
      - alert: HighErrorRate
        expr: sum(rate(http_requests_total{job="payment-gateway", code=~"5.*"}[1m])) > 0
        for: 1m
        labels:
          severity: 'critical'
        annotations:
          summary: "High error rate on payment-gateway"
          description: "More than 0 errors per minute detected on {{ $labels.instance }}."
          
      - alert: HighRequestLatency
        expr: avg(rate(http_request_duration_seconds_sum{job="payment-gateway"}[5m])) / avg(rate(http_request_duration_seconds_count{job="payment-gateway"}[5m])) > 0.5
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "High request latency"          